config/routes.rb
Rails.application.routes.draw do
  get 'docs/index', to: 'docs#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }
  root to: "home#index"
  get :search, controller: :home

  resources :users do
    collection {post :import}
  end

  resources :channels do
    resources :posts do
      get 'tag/:tag', to: 'posts#index', as: :tag
    end
  end

  resources :posts do
    resources :comments
  end

  namespace :charts do
    get "index"
    get "new-posts"
    get "new-posts-per-channel"
    get "posts-day-user"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :posts, inverse_of: :channel, dependent: :delete_all
  accepts_nested_attributes_for :posts, reject_if: :all_blank, allow_destroy: true
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: [:show, :edit, :update, :destroy]

  # GET /channels
  # GET /channels.json
  def index
    @channels = Channel.all
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
    @posts = @channel.posts
    @post = Channel.find(params[:id])
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = Channel.new(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1
  # PATCH/PUT /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def channel_params
      params.require(:channel).permit(:title, :description, :isClosed, :isDeleted, :isPrivate, posts_attributes:[:id, :post_title, :body, :user_id, :channel_id, :isDeleted, :isEdited, :isPrivate, {tag_list: []}, :_destroy])
    end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_form.html.erb
<%= form_with(model: @channel, local: true) do |form| %>
  <% if channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
      <% channel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :channel_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :channel_description %>
  </div>

    <div class="waves-effect waves-light btn", style="display: inline-block;">
      <%= form.submit %>
    </div>

    <div style="display: inline-block;">
      <a class="waves-effect waves-light btn" href="<%= channels_path %>">Back</a>
    </div>
<% end %>

app/views/channels/edit.html.erb
<h1>Editing Channel</h1>
<% if current_user.superadmin_role %>

<%= render 'form', channel: @channel %>

<%= link_to 'Show', @channel %> |
<%= link_to 'Back', channels_path %>
<% else %>
    <h2>You are being redirected to homepage due to insufficient access.
      <script>setTimeout(function(){window.location.href="/"},3000);</script></h2>
<% end %>

app/views/channels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Channel</h1>

<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Actions</th>
    <th colspan="2"></th>
  </tr>
  </thead>

  <tbody>
  <% @channels.each do |channel| %>
      <tr>
        <% unless channel.isDeleted %>
          <td><a href="<%= channel_posts_path(channel) %>"><%= channel.title %></a></td>
          <td><%= channel.description %></td>
          <% if current_user.superadmin_role? %>
              <td><%= link_to 'Edit', edit_channel_path(channel) %></td>
              <td><%= link_to 'Destroy', channel, method: :delete, data: { confirm: 'Are you sure? Deleting this channel will removes all posts and comments.' } %></td>
          <% else %>
              <td colspan="2"><p>Latest post:</p>
                <% if channel.posts.any? %>
                      <a href="<%= channel_posts_path(channel,channel.posts.last)%>"><%= channel.posts.last.post_title %></a> by <%= channel.posts.last.user.user_name%></p></td>
                <% else %>
                  <p>No posts yet.</p>
                <% end %>

                <% end %>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<br>
<% if current_user.superadmin_role? %>
    <a class="waves-effect waves-light btn" href="<%= new_channel_path %>">New Channel</a>
<% else %>
<% end %>

app/views/channels/new.html.erb
<h1>New Channel</h1>

<%= render 'form', channel: @channel %>

<!--<#= link_to 'Back', channels_path %>-->

app/views/channels/show.html.erb
<h1><%= @channel.title %></h1>
    <%= @channel.description %> <hr>
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_channel_path(@channel) %> |
<%= link_to 'Back', channels_path %>