config/routes.rb
Rails.application.routes.draw do
  get 'docs/index', to: 'docs#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }
  root to: "home#index"
  get :search, controller: :home

  resources :users do
    collection {post :import}
  end

  resources :channels do
    resources :posts do
      get 'tag/:tag', to: 'posts#index', as: :tag
    end
  end

  resources :posts do
    resources :comments
  end

  namespace :charts do
    get "index"
    get "new-posts"
    get "new-posts-per-channel"
    get "posts-day-user"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post, required: false
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  # GET /posts/:post_id/comments
  # GET /posts/:post_id/comments.xml
  def index
    # 1st you retrieve the post thanks to params[:post_id]
    @post = Post.find(params[:post_id])
    # 2nd you get all the comments of this post
    @comments = @post.comments

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /posts/:post_id/comments/:id
  # GET /comments/:id.xml
  def show
    # 1st you retrieve the post thanks to params[:post_id]
    post = Post.find(params[:post_id])
    # 2nd you retrieve the comment thanks to params[:id]
    @comment = post.comments.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json  { render json: @comment }
    end
  end

  # GET /posts/:post_id/comments/new
  # GET /posts/:post_id/comments/new.xml
  def new
    # 1st you retrieve the post thanks to params[:post_id]
    post = Post.find(params[:post_id])
    # 2nd you build a new one
    @comment = post.comments.build
    @comment.user = current_user

    respond_to do |format|
      format.html # new.html.erb
      format.json  { render json: @comment }
    end
  end

  # GET /posts/:post_id/comments/:id/edit
  def edit
    # 1st you retrieve the post thanks to params[:post_id]
    post = Post.find(params[:post_id])
    # 2nd you retrieve the comment thanks to params[:id]
    @comment = post.comments.find(params[:id])
  end

  # POST /posts/:post_id/comments
  # POST /posts/:post_id/comments.xml
  def create
    # 1st you retrieve the post thanks to params[:post_id]
    post = Post.find(params[:post_id])
    # 2nd you create the comment with arguments in params[:comment]
    @comment = post.comments.create(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        # 1st argument of redirect_to is an array, in order to build the correct route to the nested resource comment
        format.html { redirect_to channel_posts_path(post.channel, post) }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/:post_id/comments/:id
  # PUT /posts/:post_id/comments/:id.xml
  def update
    # 1st you retrieve the post thanks to params[:post_id]
    post = Post.find(params[:post_id])
    # 2nd you retrieve the comment thanks to params[:id]
    @comment = post.comments.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        # 1st argument of redirect_to is an array, in order to build the correct route to the nested resource comment
        format.html { redirect_to [@comment.post, @comment] }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/:post_id/comments/1
  # DELETE /posts/:post_id/comments/1.xml
  def destroy
    #1st you retrieve the post thanks to params[:post_id]
    post = Post.find(params[:post_id])
    #2nd you retrieve the comment thanks to params[:id]
    @comment = post.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      #1st argument reference the path /posts/:post_id/comments/
      format.html { redirect_to channel_posts_path(post.channel, post) }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:user_id, :body, :post_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@comment.post, @comment], remote:true ) do |form| %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :comment_body %>
  </div>


  <div class="waves-effect waves-light btn", style="display: inline-block;">
    <%= form.submit "Post comment" %>
  </div>

  <div style="display: inline-block;">
    <a class="waves-effect waves-light btn" href="<%= channel_posts_path(@comment.post) %>">Back</a>
  </div>

<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form'%>

<%= link_to 'Show', [@comment.post, @comment] %> |
<%= link_to 'Back', post_comments_path(@comment.post) %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user %></td>
        <td><%= comment.body %></td>
        <% if can? :update, comment %>
        <td><%= link_to 'Edit', edit_post_comment_path(comment.post, comment) %></td>
        <td><%= link_to 'Destroy', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_post_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post %>
</p>

<%= link_to 'Edit', edit_post_comment_path([@comment.post, @comment]) %> |
<%= link_to 'Back', post_comments_path(@comment.post) %>