config/routes.rb
Rails.application.routes.draw do
  get 'docs/index', to: 'docs#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }
  root to: "home#index"
  get :search, controller: :home

  resources :users do
    collection {post :import}
  end

  resources :channels do
    resources :posts do
      get 'tag/:tag', to: 'posts#index', as: :tag
    end
  end

  resources :posts do
    resources :comments
  end

  namespace :charts do
    get "index"
    get "new-posts"
    get "new-posts-per-channel"
    get "posts-day-user"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
require 'acts-as-taggable-on'
class Post < ApplicationRecord
  acts_as_taggable
  acts_as_taggable_on :posts
  belongs_to :user, required: false
  belongs_to :channel, required: false
  has_many :comments

  include RailsSortable::Model
  set_sortable :sort
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @channel = Channel.find(params[:channel_id])
    if params[:tag]
      @posts = @channel.posts.order(:sort).tagged_with(params[:tag])
      @posts.comments
    else
      @posts = @channel.posts.order(:sort).all
    end
    @comment = Comment.new
    @channel.posts.build
    @post = Post.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    channel = Channel.find (params[:channel_id])
    @post = channel.posts.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json  { render json: @post }
    end
  end

  # GET /posts/new
  def new
    @channel = Channel.find(params[:channel_id])
    #2nd you build a new one
    @post = @channel.posts.build
    @post.user = current_user
  end

  # GET /posts/1/edit
  def edit
    channel = Channel.find(params[:channel_id])
    #2nd you retrieve the comment thanks to params[:id]
    @comment = channel.posts.find(params[:id])
  end

  # POST /posts/:post_id/comments
  # POST /posts/:post_id/comments.xml
  def create
    channel = Channel.find(params[:channel_id])
    @post = channel.posts.create(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to channel_posts_path(channel, @post)}
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    channel = Channel.find(params[:channel_id])
    #2nd you retrieve the comment thanks to params[:id]
    @post = channel.posts.find(params[:id])
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to ([@post.channel, @post]) }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    channel = Channel.find(params[:channel_id])
    @post = channel.posts.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to channel_posts_path(channel,@post) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:post_title, :body, :user_id, :channel_id, :isDeleted, :isPrivate, :isEdited, :tag_list)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for([@post.channel, @post], remote: true) do |form| %>

  <div class="field">
    <%= form.label :post_title %>
    <%= form.text_field :post_title, id: :post_post_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :post_body %>
  </div>

  <div class="chips">
    <%= form.label :tag_list, "Tags (separated by comma)" %>
    <%= form.text_area :tag_list, id: :post_tag_list %>
  </div>


    <div class="waves-effect waves-light btn", style="display: inline-block;">
      <%= form.submit "Submit" %>
    </div>

    <div style="display: inline-block;">
      <a class="waves-effect waves-light btn" href="<%= channel_posts_path(@post.channel) %>">Back</a>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<!--<#= link_to 'Show', [@post.channel, @post] %>-->
<!--<#= link_to 'Back', channel_post_path(@post.channel)%>-->

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<h2><%= @channel.title %></h2>
       <% i=1 %>
    <% @posts.each do |post| %>
    <% if @channel.title != "Announcement"  %>
        <div style="margin-bottom: 3em; display: inline-block;">
          <a class="waves-effect waves-light btn" href="<%= new_channel_post_path(post.channel,post) %>">New Post</a>
        </div>
    <% elsif @channel.title == "Announcement" %>
        <%	if current_user.superadmin_role? || current_user.supervisor_role?  %>
            <div style="margin-bottom: 3em; display: inline-block;">
              <a class="waves-effect waves-light btn" href="<%= new_channel_post_path(post.channel,post) %>">New Post</a>
            </div>
        <%	elsif post.nil? %>
                <h4>There is no announcements yet</h4>
        <% end %>
    <% else %>
    <% end %>
    <div class="card-panel grey lighten-5 z-depth-3">
      <div class="row">
        <div class="col s12"><i><%= post.created_at.strftime("%b %-d, %Y %-I:%M %p") %></i><span style="float: right", align="right"><%= i %></span></div>
      </div>
      <div class="row">
        <div style="border-bottom: solid black", class="col s12">
          <%  if post.user.present? %>
          <span><%= post.user.user_name %></span>
          <span style="float: right">
            <div>
              <p>Join date: <%= post.user.created_at.strftime("%b %-d, %Y %-I:%M %p") %></p>
              <p>Address: <%= post.user.address %></p>
              <p>Post: <%= post.user.posts.count %></p>
            </div>
            <% else %>
            <div>No user assigned to this post</div>
            <% end %>
          </span>
        </div>
      </div>
        <h4><%= post.post_title %></h4>

        <div class="col s12"><span class="flow-text"><%= post.body %></span>
          <p>Tags: <%= raw(post.tag_list.map { |t| link_to t, channel_post_tag_path(@channel, post, t) }.join(', ')) %></p>
        </div>

        <div class="col s12 m4 l2">
          <% if post.updated_at.present? %>
            Edited at <%= post.updated_at.strftime("%b %-d, %Y %-I:%M %p") %>

          <% else %>
          <%  end %>
        </div>

        <div class="col s12 m4 l2">
        <!--<#= link_to 'Show', [post.channel, post] %>-->
            <% if can? :update, post %>
              <%= link_to 'Edit', edit_channel_post_path(post.channel, post) %>
              <%= link_to 'Delete', [post.channel, post], method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end  %>
            <!--<#= link_to 'Quote', [response.post, response], method: :delete, data: { confirm: 'Are you sure?' } %>-->
        </div>
    </div>

    <% if post.comments.present? %>
      <% post.comments.each do |comment|%>
        <div style="margin-left: 5em;", class="card-panel grey lighten-5 z-depth-3">
          <span><%= comment.body %></span> -
          <% if comment.user_id == current_user.id %>
            <span>Commented by: <a href="<%=edit_user_path(comment.user) %>"><%= comment.user.user_name %></a></span>
          <% else %>
            <span>Commented by: <%= comment.user.user_name %></span>
          <% end %>
          <span style="float: right">
            <span><%= comment.created_at.strftime("%b %-d, %Y %-I:%M %p") %></span>
            <% if can? :update, comment %>
            <span style="margin-left: 5px"><%= link_to 'Edit', edit_post_comment_path(comment.post, comment) %></span>
            <span style="margin-left: 5px"><%= link_to 'Delete', [comment.post, comment], method: :delete, data: {confirm: 'Are you sure?'} %></span>
          </span>
            <% end %>
        </div>
      <% end %>

    <% else %> There is no comments in this post
    <% end %>


    <div style="margin-bottom: 8em" class="comments">
      <section class="comments-box">
        <div class="add-a-comment">
          <button type="button" style="float: right" class="waves-effect waves-light btn">add a comment</button>
        </div>
        <div class="form">
        <%= form_for [post, @comment]  do |form| %>
              <%= form.text_area :body, id: :comment_body %>
              <%= form.submit 'submit',class: "add-a-comment waves-effect waves-light btn"  %>
        <% end %>
        </div>
      </section>
    </div>
    <hr>
    <% i = i + 1 %>
    <% end %>

<br>

<div style="margin-bottom: 3em; display: inline-block;">
  <a class="waves-effect waves-light btn" href="<%= channels_path %>">Back</a>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<!--<#= link_to 'Back', posts_path %>-->

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post title:</strong>
  <%= @post.post_title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<p>
  <strong>Channel:</strong>
  <%= @post.channel.title %>
</p>

<p>
  <strong>Isdeleted:</strong>
  <%= @post.isDeleted %>
</p>

<p>
  <strong>Isprivate:</strong>
  <%= @post.isPrivate %>
</p>

<!--<p>-->
  <!--<strong>Post tag:</strong>-->
  <!--<#= @post.post_tag.tag_name %>-->
<!--</p>-->

<p>
  <strong>Isedited:</strong>
  <%= @post.isEdited %>
</p>

<%= link_to 'Edit', edit_channel_post_path(@post.channel, @post) %> |
<%= link_to 'Back', channel_posts_path(@post.channel) %>