config/routes.rb
Rails.application.routes.draw do
  get 'docs/index', to: 'docs#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }
  root to: "home#index"
  get :search, controller: :home

  resources :users do
    collection {post :import}
  end

  resources :channels do
    resources :posts do
      get 'tag/:tag', to: 'posts#index', as: :tag
    end
  end

  resources :posts do
    resources :comments
  end

  namespace :charts do
    get "index"
    get "new-posts"
    get "new-posts-per-channel"
    get "posts-day-user"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Discussion Board</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--<link href="build/toastr.min.css" rel="stylesheet" type="text/css"/>-->
  </head>

  <body>
    <nav class="navbar-extended">
    <div class="nav-wrapper">
      <ul class="left hide-on-med-and-down">
        <li><a href="<%= root_path %>">Home</a></li>
          <% if user_signed_in? %>
            <% if current_user.superadmin_role? %>
              <li><a href="<%= users_path %>">Manage Users</a></li>
              <li><a href="<%= charts_index_path %>">Reports</a></li>
              <li><a href="<%= rails_admin_path %>">Admin Dashboard</a></li>
          <% elsif current_user.supervisor_role? %>
              <li><a href="<%= charts_index_path %>">Reports</a></li>
           <% else %>
            <% end %>
            <li><a href="<%= user_path(current_user) %>">My Posts</a></li>
            <li><a href="<%= docs_index_path %>">Documentation</a></li>
            <li><a href="<%= channels_path %>">Channel</a></li>
          <% end %>
      </ul>
      <ul class="right hide-on-med-and-down">
        <li><div class="hide-on-med-and-down">
          <%= form_with url: search_path, local: true, method: :get, html: { class: 'eac-sqare' } do |form| %>
              <%= form.text_field :q, placeholder: "Search", data: { behavior: "autocomplete" }, style: 'background-repeat: no-repeat; background-position:right 10px center; ' %>

          <% end %>
        </div></li>
        <% if user_signed_in? %>
            <li>Welcome, <%= current_user.user_name %></li>
            <li><%= link_to('Change password', edit_user_registration_path) %></li>
            <li><%= link_to('Edit Profile', edit_user_path(current_user.id)) %></li>
            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
        <% else %>
            <li><%= link_to('Register', new_user_registration_path) %></li>
            <li><%= link_to('Login', new_user_session_path) %></li>
        <% end %>
      </ul>
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>
  </body>

  <footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">CIS 4339</h5>
        <p class="grey-text text-lighten-4">Any comments on our applications are appreciated.</p>
        <p class="grey-text text-lighten-4">Please email us your opinion.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Professor: Keith Lancaster</h5>
        <ul> Team members:
          <li><a class="grey-text text-lighten-3" href="#!">Chris Nguyen</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Shaheer Kalim</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Shezad Kerai</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Roger Vo</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Tin Nguyen</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      All stylesheet materials are powered by Materialized CSS
      <a class="blue-text text-lighten-4 right" href="https://www.uh.edu">University of Houston</a>
    </div>
  </div>
</footer>
  <% unless flash.empty? %>
    <script type="text/javascript">
        <% flash.each do |f| %>
        <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
        toastr['<%= type %>']('<%= f[1] %>');
        <% end %>
    </script>
<% end %>
</html>